[workspace]
members = [
    "ton_abi",
    "ton_sdk",
    "ton_client/client"
]

exclude = [
    "wallet_client",
    "ton_client/platforms/ton-client-node-js",
    "ton_client/platforms/ton-client-web",
    "ton_client/platforms/ton-client-react-native"
]
