[package]
license = "Apache-2.0"
[workspace]
members = [
    "ton_sdk",
    "ton_client/client"
]
exclude = [
    "ton_client/platforms/ton-client-node-js",
    "ton_client/platforms/ton-client-web",
    "ton_client/platforms/ton-client-react-native"
]
