[workspace]
members = [
    "ton_sdk",
    "ton_client/client",
    "ton_sdk_cli",
    "api_doc/api_doc_test",
]

exclude = [
    "ton_client/platforms/ton-client-node-js",
    "ton_client/platforms/ton-client-web",
    "ton_client/platforms/ton-client-react-native"
]
