[package]
name = "ton_client_react_native"
version = "0.25.2"
authors = ["Michael Vlasov"]
license = "Apache-2.0"

[lib]
name = "tonclient"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"
jni = { version = "0.12.0", optional = true, default-features = false }

[dependencies.ton_client]
path = "../../client"
default-features = false

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.12.0", default-features = false }

[profile.release]
lto = true
