[package]
name = "graphite"
version = "0.1.0"
edition = "2018"

[lib]
name = "graphite"
crate-type = ["rlib"]

[dependencies]
websocket = "0.22.4"
reqwest = "0.9.18"
serde_json = "1.0.39"
tokio = "0.1.21"
tokio-core = "0.1.17"
futures = "0.1.27"
