[package]
authors = [ 'TON Labs LTD <support@tonlabs.io>' ]
edition = '2018'
name = 'api_info'
version = '1.28.0'

[dependencies]
serde = '1.0.115'
serde_derive = '1.0.104'
serde_json = '1.0.57'

[lib]
name = 'api_info'

