[package]
name = "api_info"
version = "1.2.0"
authors = ["Michael Vlasov <melsomino@gmail.com>"]
edition = "2018"

[lib]
name = "api_info"

[dependencies]
serde = "1.0.115"
serde_json = "1.0.57"
serde_derive = "1.0.104"
