[package]
name = "api_info"
version = "1.8.0"
authors = ["TON DEV SOLUTIONS LTD <support@tonlabs.io>"]
edition = "2018"

[lib]
name = "api_info"

[dependencies]
serde = "1.0.115"
serde_json = "1.0.57"
serde_derive = "1.0.104"
