[package]
name = "ton_client_node_js"
version = "0.25.1"
authors = ["Michael Vlasov"]
license = "Apache-2.0"

[lib]
name = "tonclient"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"

[dependencies.ton_client]
path = "../../client"
default-features = false

[profile.release]
lto = true
