[package]
name = "tonclientnodejs"
version = "0.18.0"
authors = ["Michael Vlasov"]

[lib]
name = "tonclientnodejs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"

[dependencies.ton_client]
path = "../../client"
default-features = false

[profile.release]
lto = true

