[package]
authors = [ 'TON Labs LTD <support@tonlabs.io>' ]
edition = '2018'
name = 'api_derive'
version = '1.39.0'

[dependencies]
quote = '1.0'
serde_json = '1.0.57'
api_info = { path = '../info' }
syn = { features = [ 'full' ], version = '1.0' }

[lib]
proc-macro = true
